import React from 'react';
import { CheckCircle2,  ArrowRightCircle } from 'lucide-react';

const Roadmap = ({ steps }) => {
  if (!steps || steps.length === 0) return null;

  return (
    <div className="bg-legalCharcoal/50 border border-gold/20 rounded-xl p-8 shadow-2xl animate-fade-in">
      <div className="flex items-center gap-3 mb-10 border-b border-gold/10 pb-4">
        <div className="p-2 bg-gold/10 rounded-lg">
          <ArrowRightCircle className="text-gold" size={24} />
        </div>
        <div>
          <h3 className="font-cinzel text-xl text-white tracking-widest uppercase">Action Roadmap</h3>
          <p className="text-silver/40 text-[10px] uppercase tracking-tighter">Strategic Legal Steps Generated by NyayMitra</p>
        </div>
      </div>

      <div className="relative">
        {/* The Vertical Line Path */}
        <div className="absolute left-[15px] top-2 bottom-2 w-[2px] bg-gradient-to-b from-gold via-gold/50 to-transparent"></div>

        <div className="space-y-12">
          {steps.map((step, index) => (
            <div key={index} className="relative flex items-start group">
              {/* The Glowing Dot */}
              <div className="absolute left-0 flex items-center justify-center">
                <div className="w-8 h-8 rounded-full bg-legalBlack border-2 border-gold flex items-center justify-center z-10 group-hover:shadow-[0_0_15px_rgba(212,175,55,0.6)] transition-all duration-300">
                  <span className="text-gold text-xs font-bold">{index + 1}</span>
                </div>
              </div>

              {/* The Step Content */}
              <div className="ml-14 pt-1">
                <div className="bg-white/5 border border-white/10 p-5 rounded-lg group-hover:border-gold/30 group-hover:bg-gold/5 transition-all duration-300">
                  <h4 className="text-gold font-bold text-sm uppercase tracking-wider mb-2 flex items-center gap-2">
                    <CheckCircle2 size={14} className="opacity-50" />
                    Phase {index + 1}
                  </h4>
                  <p className="text-silver leading-relaxed font-serif text-lg">
                    {step}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Footer Warning */}
      <div className="mt-12 p-4 bg-yellow-900/10 border border-yellow-700/20 rounded-md">
        <p className="text-[10px] text-yellow-600/60 text-center uppercase tracking-widest leading-4">
          Disclaimer: This roadmap is AI-generated for informational purposes. <br /> 
          Please consult a certified legal advocate for formal representation.
        </p>
      </div>
    </div>
  );
};

export default Roadmap;