import React from 'react';
import { motion } from 'framer-motion';
import { CheckCircle2, ArrowRightCircle, Sparkles } from 'lucide-react';

const Roadmap = ({ steps, lang }) => {
  if (!steps || steps.length === 0) return null;

  // Stagger animation container
  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.15 }
    }
  };

  const item = {
    hidden: { opacity: 0, x: -20 },
    show: { opacity: 1, x: 0 }
  };

  return (
    <motion.div 
      initial="hidden"
      animate="show"
      variants={container}
      className="bg-legalCharcoal/50 border border-gold/20 rounded-xl p-8 shadow-2xl backdrop-blur-sm"
    >
      {/* Header Section */}
      <div className="flex items-center justify-between mb-10 border-b border-gold/10 pb-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-gold/10 rounded-lg shadow-[0_0_10px_rgba(212,175,55,0.1)]">
            <ArrowRightCircle className="text-gold" size={24} />
          </div>
          <div>
            <h3 className="font-cinzel text-xl text-white tracking-widest uppercase">
              {lang === 'hi' ? "कार्ययोजना (Roadmap)" : "Action Roadmap"}
            </h3>
            <p className="text-silver/40 text-[10px] uppercase tracking-tighter">
              {lang === 'hi' 
                ? "न्यायमित्र द्वारा तैयार किए गए रणनीतिक कानूनी कदम" 
                : "Strategic Legal Steps Generated by NyayMitra"}
            </p>
          </div>
        </div>
        <Sparkles className="text-gold/20 animate-pulse" size={20} />
      </div>

      <div className="relative">
        {/* Animated Vertical Line Path */}
        <motion.div 
          initial={{ height: 0 }}
          animate={{ height: '100%' }}
          transition={{ duration: 1.5, ease: "easeInOut" }}
          className="absolute left-[15px] top-2 w-[2px] bg-gradient-to-b from-gold via-gold/50 to-transparent origin-top"
        ></motion.div>

        <div className="space-y-12">
          {steps.map((step, index) => (
            <motion.div 
              key={index} 
              variants={item}
              className="relative flex items-start group"
            >
              {/* The Glowing Number Dot */}
              <div className="absolute left-0 flex items-center justify-center">
                <div className="w-8 h-8 rounded-full bg-legalBlack border-2 border-gold flex items-center justify-center z-10 group-hover:scale-110 group-hover:shadow-[0_0_20px_rgba(212,175,55,0.4)] transition-all duration-300">
                  <span className="text-gold text-xs font-bold">{index + 1}</span>
                </div>
              </div>

              {/* The Step Content Card */}
              <div className="ml-14 pt-1 w-full">
                <div className="bg-white/5 border border-white/10 p-5 rounded-lg group-hover:border-gold/40 group-hover:bg-gold/5 group-hover:translate-x-2 transition-all duration-300">
                  <div className="flex justify-between items-center mb-2">
                    <h4 className="text-gold font-bold text-xs uppercase tracking-[0.2em] flex items-center gap-2">
                      <CheckCircle2 size={14} className="text-gold/60" />
                      {lang === 'hi' ? `चरण ${index + 1}` : `Phase ${index + 1}`}
                    </h4>
                  </div>
                  <p className={`${lang === 'hi' ? 'text-xl font-normal' : 'text-lg font-serif'} text-silver leading-relaxed`}>
                    {step}
                  </p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Footer Warning */}
      <div className="mt-12 p-4 bg-yellow-900/10 border border-yellow-700/20 rounded-md">
        <p className="text-[9px] text-yellow-600/60 text-center uppercase tracking-widest leading-4">
          {lang === 'hi' 
            ? "अस्वीकरण: यह रोडमैप सूचनात्मक उद्देश्यों के लिए AI द्वारा तैयार किया गया है। कृपया कानूनी सलाह के लिए वकील से संपर्क करें।"
            : "Disclaimer: This roadmap is AI-generated for informational purposes. Please consult a certified legal advocate for formal representation."}
        </p>
      </div>
    </motion.div>
  );
};

export default Roadmap;